<a href="https://colab.research.google.com/github/mstfahmidazaman1320-lab/PYTHON-code/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4])

print("Vector: {}".format(vector))

print("Shape: {}".format(vector.shape))

print("Dim: {}".format(vector.ndim))

print("Data type: {}".format(vector.dtype))

Vector: [1 2 3 4]
Shape: (4,)
Dim: 1
Data type: int64


In [ ]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

v.shape = (2, 3, 2)

print(v)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

v.shape = (1, 2, 7)

print(v)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]]


In [ ]:
v = np.zeros((2, 3, 2))

print(v)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
a = np.arange(15)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
print("Zeros")

a = np.zeros((3, 3))

print("A: {}".format(a))

b = np.zeros_like(a)

print("B: {}".format(b))

print("\nOnes")

a = np.ones((3, 3))

print("A: {}".format(a))

b = np.ones_like(a)

print("B: {}".format(b))

print("\nEmpty")

a = np.empty((3, 3))

print("A: {}".format(a))

b = np.empty_like(a)

print("B: {}".format(b))

Zeros
A: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.array([1, 2, 3, 4.5, 6.7])
print("A: {}, dtype: {}".format(a, a.dtype))
b = a.astype(int)
print("B: {}, dtype: {}".format(b, b.dtype))

A: [1.  2.  3.  4.5 6.7], dtype: float64
B: [1 2 3 4 6], dtype: int64


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])

c = a + b
print(c)

c = a * b
print(c)

c = a - b
print(c)

[[5 7 9]
 [5 7 9]]
[[ 4 10 18]
 [ 4 10 18]]
[[-3 -3 -3]
 [ 3  3  3]]


In [ ]:
a = 3
b = np.array([[1, 2, 3], [4, 5, 6]])

c = a + b
print(c)

c = a * b
print(c)

c = 1.0 / b
print(c)

[[4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [ ]:
a = np.arange(20)
print(a)
a[10:15] = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9  5  5  5  5  5 15 16 17 18 19]


In [ ]:
a = np.arange(20)
print(a)
b = a[10:15].copy()
b = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[:, 0]

array([1, 4, 7])

In [ ]:
a = np.array(["Mayur", "is", "an", "awesome", "coder"])
a == "Mayur"

array([ True, False, False, False, False])

In [ ]:
a[~(a == "Mayur")]

array(['is', 'an', 'awesome', 'coder'], dtype='<U7')

In [ ]:
(a == "Mayur") | (a == "coder")

array([ True, False, False, False,  True])

In [ ]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a)
a[[1, 3, 2]]

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


array([[2, 2, 2],
       [4, 4, 4],
       [3, 3, 3]])

In [ ]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a.T)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
a = 20
b = np.random.rand(2, 2)
print(np.exp(a))
print(np.exp(b))

485165195.4097903
[[1.44525288 1.22845053]
 [1.59129597 1.08097127]]


In [ ]:
a = np.random.rand(3, 3)
print(a)
print(np.mean(a))
print(a.mean())

print(np.std(a))

[[0.27795644 0.34101469 0.43238775]
 [0.44698962 0.30324877 0.44458566]
 [0.68649149 0.0832103  0.97459596]]
0.4433867403704917
0.4433867403704917
0.24235682857740037
